### ISSUE TITLE
PlatformException(channel-error, Unable to establish connection on channel., null, null)

### ISSUE THREAD

**Issue by LUK3D** [the-meedu-app/flutter-meedu-player#44]
i'm getting this error. How can i fix it?

I/flutter ( 7177): PlatformException(channel-error, Unable to establish connection on channel., null, null)
I/flutter ( 7177): #0      VideoPlayerApi.create (package:video_player_platform_interface/messages.dart:174:7)
I/flutter ( 7177): <asynchronous suspension>
I/flutter ( 7177): #1      MethodChannelVideoPlayer.create (package:video_player_platform_interface/method_channel_video_player.dart:46:31)
I/flutter ( 7177): <asynchronous suspension>
I/flutter ( 7177): #2      VideoPlayerController.initialize (package:video_player/video_player.dart:292:19)
I/flutter ( 7177): <asynchronous suspension>
I/flutter ( 7177): #3      MeeduPlayerController._initializePlayer (package:meedu_player/src/controller.dart:214:5)
I/flutter ( 7177): <asynchronous suspension>
I/flutter ( 7177): #4      MeeduPlayerController.setDataSource (package:meedu_player/src/controller.dart:291:7)
I/flutter ( 7177): <asynchronous suspension>

**Comment by darwin-morocho** [comment]
@LUK3D csn you add a reproducible code?
